# Generated by Django 6.0.4 on 2026-04-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('KAFE', 'Kafe'), ('KUTUPHANE', 'Kütüphane'), ('ECZANE', 'Eczane'), ('RESTORAN', 'Restoran')], max_length=20)),
                ('adres', models.TextField()),
                ('su_an_acik', models.BooleanField(default=True)),
                ('doluluk_orani', models.IntegerField(default=0, help_text='Yüzde olarak doluluk (Örn: 80)')),
                ('wifi_var', models.BooleanField(default=False)),
                ('priz_var', models.BooleanField(default=False)),
            ],
        ),
    ]
