# Generated by Django 6.0.4 on 2026-04-22 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='favorileyenler',
            field=models.ManyToManyField(blank=True, related_name='favori_mekanlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
