# Generated by Django 6.0.4 on 2026-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_mekan_favorileyenler'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mekanlar/', verbose_name='Mekan Fotoğrafı'),
        ),
    ]
