# Generated by Django 6.0.4 on 2026-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_mekan_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='acilis_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Açılış Saati'),
        ),
        migrations.AddField(
            model_name='mekan',
            name='bahce_var',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='canli_muzik_var',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='cocuk_oyun_alani_var',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='engelli_erişimi_var',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='evcil_hayvan_izinli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='kapanis_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Kapanış Saati'),
        ),
        migrations.AddField(
            model_name='mekan',
            name='otopark_var',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='sigara_icin_uygun',
            field=models.BooleanField(default=False),
        ),
    ]
