# Generated by Django 6.0.4 on 2026-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_mekan_acilis_saati_mekan_bahce_var_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mekan',
            old_name='engelli_erişimi_var',
            new_name='engelli_erisimi_var',
        ),
    ]
