# Generated by Django 6.0.4 on 2026-04-23 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_rename_engelli_erişimi_var_mekan_engelli_erisimi_var'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Yorumunuz')),
                ('fotoğraf', models.ImageField(blank=True, null=True, upload_to='yorum_fotolari/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='venues.mekan')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
