# Generated by Django 5.2.4 on 2026-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_yorum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
