# Generated by Django 6.0.4 on 2026-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_mekan_id_alter_yorum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekan',
            name='kategori',
            field=models.CharField(choices=[('KAFE', 'Kafe'), ('KUTUPHANE', 'Kütüphane'), ('ECZANE', 'Eczane'), ('RESTORAN', 'Restoran'), ('PUB', 'Pub')], max_length=20),
        ),
    ]
