# Generated by Django 6.0.4 on 2026-05-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_mekan_anlik_duyuru_mekan_dogrulanmis_mi_mekan_sahibi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mekan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mekan',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='mekan',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='anlik_duyuru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Etkinlik Başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('baslangic', models.DateTimeField(verbose_name='Başlangıç')),
                ('bitis', models.DateTimeField(verbose_name='Bitiş')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='etkinlikler/', verbose_name='Afiş / Fotoğraf')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkinlikler', to='venues.mekan')),
            ],
        ),
    ]
