# Generated by Django 6.0.5 on 2026-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_mekan_sehir'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='2FA doğrulama tamamlandı mı?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret_key',
            field=models.CharField(blank=True, default='', help_text='TOTP gizli anahtarı', max_length=32),
        ),
    ]
