# Generated by Django 6.0.5 on 2026-05-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_profile_is_verified_profile_totp_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mekan',
            name='ruhsat_belgesi',
            field=models.ImageField(blank=True, null=True, upload_to='ruhsatlar/', verbose_name='Ruhsat Belgesi'),
        ),
    ]
