# Generated by Django 5.2.4 on 2026-05-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_mekan_is_approved_mekan_ruhsat_belgesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
