# Generated by Django 5.2.4 on 2026-05-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_alter_etkinlik_id_alter_mekan_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='puan',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Puan (1-5)'),
        ),
    ]
