# Generated by Django 5.2.4 on 2026-05-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_yorum_puan_alani'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil_fotolari/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
