# Generated by Django 5.2.4 on 2026-05-28 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='goruntuleme_sayisi',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.CreateModel(
            name='MekanFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='mekan_fotolari/', verbose_name='Fotoğraf')),
                ('siralama', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('yuklenme', models.DateTimeField(auto_now_add=True)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotolar', to='venues.mekan')),
            ],
            options={
                'verbose_name': 'Mekan Fotoğrafı',
                'ordering': ['siralama', 'yuklenme'],
            },
        ),
    ]
