# Generated by Django 5.2.4 on 2026-05-28 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_goruntuleme_ve_galeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='YorumFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='yorum_fotolari/')),
                ('yuklenme', models.DateTimeField(auto_now_add=True)),
                ('yorum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotolar', to='venues.yorum')),
            ],
            options={
                'ordering': ['yuklenme'],
            },
        ),
    ]
