# Generated by Django 5.2.4 on 2026-05-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_yorum_coklu_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SifreSifirlamaKodu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=6)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('kullanildi', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sifre_kodlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
    ]
