# Generated by Django 5.2.4 on 2026-05-28 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_sifre_sifirlama_kodu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='menu_foto',
            field=models.ImageField(blank=True, null=True, upload_to='menuler/', verbose_name='Menü Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='mekan',
            name='menu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='menuler/', verbose_name='Menü PDF'),
        ),
        migrations.AddField(
            model_name='mekan',
            name='rezervasyon_aktif',
            field=models.BooleanField(default=False, verbose_name='Rezervasyon Kabul Et'),
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('YORUM', 'Yeni Yorum'), ('BEGENI', 'Beğeni'), ('TAKIP', 'Takipçi'), ('ONAY', 'Mekan Onayı'), ('YANIT', 'Yanıt'), ('KAMPANYA', 'Kampanya'), ('REZERVASYON', 'Rezervasyon'), ('DUYURU', 'Duyuru')], max_length=15)),
                ('mesaj', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('okundu', models.BooleanField(default=False)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gonderilen_bildirimler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='Kampanya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('baslangic', models.DateTimeField(verbose_name='Başlangıç')),
                ('bitis', models.DateTimeField(verbose_name='Bitiş')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='kampanyalar/')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kampanyalar', to='venues.mekan')),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='MekanListesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Liste Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('herkese_acik', models.BooleanField(default=True, verbose_name='Herkese Açık')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('mekanlar', models.ManyToManyField(blank=True, related_name='listeler', to='venues.mekan')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mekan_listeleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('kisi_sayisi', models.PositiveIntegerField(default=1, verbose_name='Kişi Sayısı')),
                ('not_mesaj', models.TextField(blank=True, verbose_name='Not')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi'), ('IPTAL', 'İptal Edildi')], default='BEKLIYOR', max_length=15)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervasyonlarim', to=settings.AUTH_USER_MODEL)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervasyonlar', to='venues.mekan')),
            ],
            options={
                'ordering': ['-tarih', '-saat'],
            },
        ),
        migrations.CreateModel(
            name='YorumYanit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Yanıt')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('guncellendi', models.DateTimeField(auto_now=True)),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yorum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yanit', to='venues.yorum')),
            ],
        ),
        migrations.CreateModel(
            name='CalismaGunu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')])),
                ('acik', models.BooleanField(default=True)),
                ('acilis', models.TimeField(blank=True, null=True)),
                ('kapanis', models.TimeField(blank=True, null=True)),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisma_gunleri', to='venues.mekan')),
            ],
            options={
                'ordering': ['gun'],
                'unique_together': {('mekan', 'gun')},
            },
        ),
        migrations.CreateModel(
            name='Takip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('takip_edilen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takipcileri', to=settings.AUTH_USER_MODEL)),
                ('takipci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takip_ettikleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('takipci', 'takip_edilen')},
            },
        ),
        migrations.CreateModel(
            name='YorumBegeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begendigi_yorumlar', to=settings.AUTH_USER_MODEL)),
                ('yorum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begeniler', to='venues.yorum')),
            ],
            options={
                'unique_together': {('yorum', 'kullanici')},
            },
        ),
    ]
