# Generated by Django 5.2.4 on 2026-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_doluluk_orani_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='calisma_alani_var',
            field=models.BooleanField(default=False, verbose_name='Çalışma Alanı'),
        ),
    ]
